export const SIGN_UP = '/sign-up'
export const SIGN_IN = '/sign-in'
export const HOME = '/'
export const ACCOUNT = '/account'
export const PASSWORD_FORGET = '/forget-password'
export const ATHLET_ADD = '/add'
export const ATHLET_EDIT = '/:id/edit'
